####
# ./mvnw -f handlebars/ package -Pnative
# docker build -f handlebars/src/main/docker/Dockerfile.native -t daggerok/quarkus-vertx-template-engines-handlebars-native .
# docker run -i --rm -p 8080:8080 -v $(pwd)handlebars-/src/main/resources/templates:/work/templates daggerok/quarkus-vertx-template-engines-handlebars-native
###
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
